import Head from 'next/head'
import Image from 'next/image'

import Header from '../components/Header'
import Nav from '../components/Nav'
import RequestedVideos from '../components/RequestedVideos'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Twolu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        {/* Header */}
        <Header />
        {/* Categories Nav */}
        <Nav />
        {/* Content Grid */}
        <RequestedVideos />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const requestedGenre = context.query.genre;

  
}
